#!/bin/sh

## hyphop ##

GIT=khadas-busybox
NAME=busybox
VER=1.30.1
PKG="$NAME-$VER.tar.bz2"
PKGD="$NAME-$VER"
ZDIR=../
WDIR=../khadas-busybox-wdir
BDIR="$WDIR/$NAME"
SRV=https://www.busybox.net/downloads/
SRC="$SRV$PKG"
CDIR="$PWD"
LOG=log
INITRAMFS_DIR="$WDIR/initramfs.bb"

## dropbear 

DB_PK=dropbear-2019.78
DB_PKG=$DB_PK.tar.bz2
