#!/bin/sh

## hyphop ##

	ln -s /usr/sbin/dropbear /usr/bin/dropbearkey
	ln -s /usr/sbin/dropbear /usr/bin/scp
	ln -s /usr/sbin/dropbear /usr/bin/dbclient
	ln -s /usr/sbin/dropbear /usr/bin/ssh
	ln -s /usr/sbin/dropbear /usr/bin/dropbearconvert

    for keytype in rsa; do
	# check for keys
	key=dropbear/dropbear_${keytype}_host_key


	[ -f /tmp/$key -o -s /etc/$key ] || {
	    echo "[i] ssh key gen $key">&2;
	    # generate missing keys
	    mkdir -p /tmp/dropbear
	    [ -x /usr/bin/dropbearkey ] && {
		/usr/bin/dropbearkey -t $keytype -f /tmp/$key 
	    } 
	}

    done

    mkdir -p /etc/dropbear
    mv /tmp/dropbear/dropbear_* /etc/dropbear/
    chown root /etc/dropbear
    chmod 0700 /etc/dropbear

    logger -t sys "ssh starting"

